
# cargo install dioxus-cli # --git https://github.com/Dioxuslabs/cli

[application]
name = "wcnvs" # App (Project) Name
asset_dir = "assets" # resource (public) file folder
out_dir = "dist" # `build` & `serve` dist path

default_platform = "web" # Dioxus App Default Platform: desktop, web, mobile, ssr

[web.app]
title = "dioxus | ⛺" # HTML title tag content
#index_on_404 = true
#base_path = "indiox"

[web.watcher]
reload_html = true # when watcher trigger, regenerate the `index.html`
watch_path = [ "src", "assets" ] # which files or dirs will be watcher monitoring

[web.resource] # include `assets` in web platform
#style = ["tailwind.css"] # CSS style file
script = [] # Javascript code file

[web.resource.dev]
script = [] # Javascript code file, serve: [dev-server] only

[application.tools]
# use binaryen.wasm-opt for output Wasm file
# binaryen just will trigger in `web` platform
#binaryen = { wasm_opt = true }

# default value: input = "public/tailwind.css", config = "src/tailwind.config.js"
#tailwindcss = { input = "tailwind_base.css", config = "tailwind.config.js" }
#tailwindcss = { input = "main.css", config = "tailwind.config.js" }

